### ISSUE TITLE
Implement the CheckCameraDatabase tab with a button to modify the cameras.sqlite file

### ISSUE THREAD

**Issue by alearcteam** [archeos/archeos-ppt-gui#4]
To implement the CheckCameraDatabase tab:
- insert a button to open the cameras.sqlite file.

possible solution:
- lanch SQLiteBrowser with the cameras database opened

**Comment by rjanvier** [comment]
Sqlite3 can be accessed through Python (it's in the standard library) and I also managed to redirect standard output to the central widget (thanks QProcess - see archeos-ppt-gui#1 and #2). 

But in the case of CheckCameraDatabase feature, user could be prompted to enter CCD width. This prompt is more tricky to handle, because there is no simple way (from pyQT point)to redirect output AND listening when input is needed. One of the hacky solution I've found is to parse output waiting for 'CCD witdh:' msg and then show a QDialog... but it's very hacky and dirty. 

The real issue is that most of time, I must hack ppt AND ppt-gui to do something clean. 
At the end, we will have a mountain of patch in ppt... so my point of view is to reimplement a simpler ppt (e.g. get rid of cross plateform things) inside ppt-gui. Instead of having this stack : 
- ppt-gui (calling)-> ppt (calling)-> binaries (ex VLfeat, bundler...) 
- we should have ppt-gui (calling)-> binaries. 

Of course we could keep ppt in the repos for peoples who want to run bundler in a CLI.
